#!/usr/bin/env python

import argparse
import os
import sys

from time import sleep

import zbar

DEFAULT_VIDEO_DEVICE = os.environ.get('QRKEY_VIDEO', None) or '/dev/video0'

description = 'qrkey scanner.'
parser = argparse.ArgumentParser(description=description)
parser.add_argument('-d', '--debug', action='store_true', default=False,
                    help='enable debug')


class Scanner(object):

    def __init__(self, device, debug=False):
        self._processor = zbar.Processor()
        self._processor.parse_config('enable')
        self._processor.init(device)
        self._processor.visible = debug

    def scan(self):

        try:
            self._processor.process_one()
        except zbar.WindowClosed:
            sys.exit(0)

        for symbol in self._processor.results:
            if not symbol.count:
                return symbol.type, symbol.data

if __name__ == '__main__':

    args = parser.parse_args()

    scanner = Scanner(DEFAULT_VIDEO_DEVICE, debug=args.debug)

    while True:
        _, value = scanner.scan()

        print value

        sleep(0.5)
